import { MarkerData } from "@/app/components/MapViewer/MapViewerTypes";
import { MAP_PDF_CSS } from "./map-html.css";

interface MapContentProps {
  imageUrl: string;
  imageName: string;
  markers: MarkerData[];
}

// Basic HTML escaping to avoid breaking markup / injection
function escapeHtml(input: string | undefined | null): string {
  const s = String(input ?? "");
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

// If your marker.description contains trusted HTML you want to keep,
// DO NOT escape it. Otherwise, keep escaping for safety.
// Here: safe default = escape everything.
function nl2br(text: string) {
  return text.replace(/\n/g, "<br/>");
}

export default function mapContentToHtml(props: MapContentProps): string {
  const titleText = escapeHtml(props.imageName);
  const imageUrl = escapeHtml(props.imageUrl);

  const styleTag = `<style>${MAP_PDF_CSS}</style>`;

  const markersHtml = props.markers
    .map((marker: MarkerData, idx) => {
      const title = escapeHtml(marker.title);
      const desc = marker.description ?? "";
      return `
        <div class="marker">
          <h2>${idx + 1}. ${title}</h2>
          <div class="desc">${desc}</div>
        </div>
      `;
    })
    .join("");

  const html = `
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        ${styleTag}
        <title>${titleText}</title>
      </head>
      <body>
        <div class="container">
          <h1>${titleText}</h1>

          <div class="image-wrap">
            <img src="${imageUrl}" alt="${titleText}" />
            <div class="meta">Generated by MapForge</div>
          </div>

          <div class="divider"></div>

          <h3 class="section-title">Markers (${props.markers.length})</h3>
          ${
            markersHtml ||
            `<div class="marker"><h2>No markers</h2><div class="desc">—</div></div>`
          }
        </div>
      </body>
    </html>
  `;

  return html;
}
